name: invoice_d
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Usamos la 1.0.0 que no tiene el bug de MediaQuery.boldTextOverride
  fl_chart: ^1.0.0

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  image_picker: ^1.0.0
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1
  flutter_multi_formatter: ^2.12.2
  google_mlkit_barcode_scanning: ^0.14.1
  path_provider: ^2.1.3
  firebase_storage: ^12.4.7
  image: ^4.1.3
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
